/*
 * Automatically generated C config: don't edit
 * LTIB version: 6.2.1
 */
#define AUTOCONF_INCLUDED
#define CONFIG_CONFIG_TITLE "LTIB: Sagem Communications IMX31 Homescreen board"
#define CONFIG_CPU "MX31"
#define CONFIG_PLATFORM_COMMENT "Sagem Communications IMX31 Homescreen board"
#define CONFIG_VENDOR "Sagem Communications"
#define CONFIG_PLATFORM "imx31homescreen"
#define CONFIG_GNUTARCH "arm"
#define CONFIG_LINTARCH "arm"
#define CONFIG_CFGHOST "arm-linux"
#define CONFIG_ENDIAN "little"

/*
 * Choose the target C library type
 */
#define CONFIG_GLIBC 1
#undef CONFIG_UCLIBC

/*
 * Choose your toolchain
 */
#define CONFIG_TOOLCHAIN1 1
#undef CONFIG_TOOLCHAIN2
#undef CONFIG_TOOLCHAIN_CUSTOM
#define CONFIG_TOOLCHAIN "tc-fsl-x86lnx-armeabi-nptl-4.1.1-6.i386.rpm"
#define CONFIG_TOOLCHAIN_PATH "/opt/freescale/usr/local/gcc-4.1.1-glibc-2.4-nptl-6/arm-none-linux-gnueabi"
#define CONFIG_TOOLCHAIN_PREFIX "arm-none-linux-gnueabi-"
#define CONFIG_TOOLCHAIN_CFLAGS "-O2 -fsigned-char -mabi=aapcs-linux -mfpu=vfp -mfloat-abi=softfp"

/*
 * Choose your Kernel
 */
#define CONFIG_KERNEL1 1
#undef CONFIG_KERNEL2
#undef CONFIG_KERNEL_DIR_BUILD
#undef CONFIG_KERNEL_NONE
#define CONFIG_PKG_KERNEL "kernel-2.6.19-mx"
#define CONFIG_PKG_KERNEL_PRECONFIG "linux-2.6.19-mx31-hsv3.config"
#define CONFIG_PKG_KERNEL_WANT_HEADERS 1
#undef CONFIG_PKG_KERNEL_WANT_CF
#undef CONFIG_PKG_KERNEL_LEAVESRC
#define CONFIG_DEPLOYMENT_ERASE_BLOCK_SIZE "128"
#define CONFIG_DISTRO "dist/lfs-5.1"

/*
 * Package selection
 */

/*
 * Package list
 */
#define CONFIG_PKG_ATK 1
#undef CONFIG_PKG_AUTOCONF
#undef CONFIG_PKG_AUTOMAKE
#define CONFIG_LIBC_WANTED 1
#define CONFIG_PKG_LIBC "base_libs"
#undef CONFIG_PKG_LIBC_WANT_LOCALES
#undef CONFIG_PKG_LIBC_WANT_HEADERS
#undef CONFIG_PKG_LIBC_WANT_STATIC_LIBS
#define CONFIG_PKG_ALSA_LIB 1
#define CONFIG_PKG_ALSA_UTILS 1
#undef CONFIG_PKG_BASH
#undef CONFIG_PKG_BIND
#undef CONFIG_PKG_BINUTILS
#undef CONFIG_PKG_BISON
#undef CONFIG_PKG_BLUEZ_HCIDUMP
#undef CONFIG_PKG_BLUEZ_LIBS
#undef CONFIG_PKG_BLUEZ_UTILS
#undef CONFIG_PKG_BOA
#undef CONFIG_PKG_BONNIE_PLUS_PLUS
#undef CONFIG_PKG_BRIDGE_UTILS
#define CONFIG_PKG_BUSYBOX 1
#define CONFIG_PKG_BUSYBOX_PRECONFIG "busybox.config"
#undef CONFIG_PKG_BUSYBOX_WANT_CF
#undef CONFIG_PKG_BZIP2
#define CONFIG_PKG_CAIRO 1
#undef CONFIG_PKG_CAN4LINUX
#undef CONFIG_PKG_CLAMAV
#undef CONFIG_PKG_CLUTTER
#undef CONFIG_PKG_COREUTILS
#undef CONFIG_PKG_CPIO
#undef CONFIG_PKG_CRACKLIB
#undef CONFIG_PKG_CRAMFS
#undef CONFIG_PKG_DAEMONIZER
#undef CONFIG_PKG_DEVMEM2
#undef CONFIG_PKG_DHCP
#undef CONFIG_PKG_DB1
#define CONFIG_PKG_DEV 1
#undef CONFIG_PKG_DEVFSD
#undef CONFIG_PKG_DEV_NONE
#undef CONFIG_PKG_DIFFUTILS
#undef CONFIG_PKG_DIRECTFB
#undef CONFIG_PKG_DISTCC
#undef CONFIG_PKG_DOSFSTOOLS
#undef CONFIG_PKG_DROPBEAR
#undef CONFIG_PKG_DTC
#undef CONFIG_PKG_E2FSPROGS
#undef CONFIG_PKG_ED
#undef CONFIG_PKG_ETHTOOL
#define CONFIG_PKG_EXPAT 1
#undef CONFIG_PKG_FAKEROOT
#define CONFIG_PKG_FAKE_PROVIDES 1
#undef CONFIG_PKG_FBSET
#define CONFIG_PKG_FFMPEG 1
#undef CONFIG_PKG_FINDUTILS
#undef CONFIG_PKG_FLEX
#define CONFIG_PKG_FONTCONFIG 1
#define CONFIG_PKG_FREETYPE 1
#undef CONFIG_PKG_GAWK
#undef CONFIG_PKG_GCC
#undef CONFIG_PKG_GDB
#undef CONFIG_PKG_GENEXT2FS
#undef CONFIG_PKG_GENROMFS
#undef CONFIG_PKG_GETTEXT
#define CONFIG_PKG_GLIB2 1
#undef CONFIG_PKG_GMP
#undef CONFIG_PKG_GREP
#undef CONFIG_PKG_GROFF
#define CONFIG_PKG_GSTREAMER_CORE 1
#define CONFIG_PKG_GST_PLUGINS_BASE 1
#define CONFIG_PKG_GST_PLUGINS_GOOD 1
#define CONFIG_PKG_GST_PLUGINS_BAD 1
#define CONFIG_PKG_GST_FFMPEG 1
#define CONFIG_PKG_GST_PLUGINS_UGLY 1
#define CONFIG_PKG_GTK2 1
#undef CONFIG_PKG_HDPARM
#undef CONFIG_PKG_HELLOWORLD
#undef CONFIG_PKG_HESIOD
#undef CONFIG_PKG_HOTPLUG
#undef CONFIG_PKG_HTTPD
#define CONFIG_PKG_I2C_TOOLS 1
#undef CONFIG_PKG_IPROUTE
#undef CONFIG_PKG_PIDENTD
#define CONFIG_PKG_INETUTILS 1
#undef CONFIG_PKG_IPERF
#undef CONFIG_PKG_IPSEC_TOOLS
#undef CONFIG_PKG_IPSECADM
#define CONFIG_PKG_IPTABLES 1
#define CONFIG_PKG_IPUTILS 1
#undef CONFIG_PKG_IRATTACH
#undef CONFIG_PKG_KBD
#undef CONFIG_PKG_LESS
#undef CONFIG_PKG_LFS_UTILS
#undef CONFIG_PKG_LIBICONV
#undef CONFIG_PKG_LIBID3TAG
#undef CONFIG_PKG_LIBMAD
#define CONFIG_PKG_LIBMMS 1
#define CONFIG_PKG_LIBJPEG 1
#undef CONFIG_PKG_LIBELF
#undef CONFIG_PKG_LIBPCAP
#define CONFIG_PKG_LIBPNG 1
#define CONFIG_PKG_LIBOIL 1
#undef CONFIG_PKG_LIBTERMCAP
#define CONFIG_PKG_LIBTIFF 1
#undef CONFIG_PKG_LIBTOOL
#define CONFIG_PKG_LIBUSB 1
#define CONFIG_PKG_LIBXML2 1
#undef CONFIG_PKG_LINUX_ATM
#undef CONFIG_PKG_LINUX_WLAN
#undef CONFIG_PKG_LKC
#undef CONFIG_PKG_LTP
#undef CONFIG_PKG_LMBENCH
#define CONFIG_PKG_LOGOGEN 1
#undef CONFIG_PKG_LOGOGEN_SAGEM_PRECONFIG
#define CONFIG_PKG_LOGOGEN_TELSTRA_PRECONFIG 1
#undef CONFIG_PKG_LRZSZ
#undef CONFIG_PKG_M4
#undef CONFIG_PKG_MADPLAY
#undef CONFIG_PKG_MAKE
#undef CONFIG_PKG_MAN
#undef CONFIG_PKG_MDADM
#define CONFIG_PKG_MERGE 1
#undef CONFIG_PKG_MICROWINDOWS
#undef CONFIG_PKG_MODUTILS
#define CONFIG_PKG_MODULE_INIT_TOOLS 1
#undef CONFIG_MODUTILS_NONE
#define CONFIG_PKG_MTD_UTILS 1
#undef CONFIG_PKG_MXC_MISC
#undef CONFIG_PKG_MYSQL
#define CONFIG_PKG_NCURSES 1
#define CONFIG_PKG_NCURSES_WANT_REDUCED_SET 1
#undef CONFIG_PKG_NET_TOOLS
#undef CONFIG_PKG_NETPERF
#define CONFIG_PKG_NTPCLIENT 1
#undef CONFIG_PKG_OPENSSH
#undef CONFIG_PKG_OPENSSL
#undef CONFIG_PKG_OPENSWAN
#undef CONFIG_PKG_OPROFILE
#define CONFIG_PKG_PANGO 1
#undef CONFIG_PKG_PATCH
#undef CONFIG_PKG_PCIUTILS
#undef CONFIG_PKG_PCMCIA_CS
#undef CONFIG_PKG_PCRE
#undef CONFIG_PKG_PERL
#undef CONFIG_PKG_PHP
#define CONFIG_PKG_PIXMAN 1
#undef CONFIG_PKG_POPT
#undef CONFIG_PKG_PORTMAP
#undef CONFIG_PKG_PPP
#undef CONFIG_PKG_PROCINFO
#undef CONFIG_PKG_PROCPS
#undef CONFIG_PKG_PSMISC
#undef CONFIG_PKG_PTPD
#undef CONFIG_PKG_PYTHON
#undef CONFIG_PKG_QTOPIA
#undef CONFIG_PKG_RPM
#undef CONFIG_PKG_RNG_TOOLS
#undef CONFIG_PKG_RSYNC
#undef CONFIG_PKG_SAMBA
#undef CONFIG_PKG_SASH
#undef CONFIG_PKG_SCHEDUTILS
#undef CONFIG_PKG_SCREEN
#undef CONFIG_PKG_SED
#undef CONFIG_PKG_SEQ
#undef CONFIG_PKG_SETSERIAL
#define CONFIG_PKG_SKELL 1
#undef CONFIG_PKG_SKELL_WANT_TERMINFO
#undef CONFIG_PKG_STRACE
#define CONFIG_PKG_SYSCONFIG 1
#define CONFIG_PKG_SYSFSUTILS 1
#undef CONFIG_PKG_SYSKLOGD
#undef CONFIG_PKG_SYSVINIT
#undef CONFIG_PKG_TAR
#undef CONFIG_PKG_TCPDUMP
#undef CONFIG_PKG_TCP_WRAPPERS
#undef CONFIG_PKG_TEXINFO
#undef CONFIG_PKG_TIME
#undef CONFIG_PKG_TIMEZONE
#undef CONFIG_PKG_TINYLOGIN
#define CONFIG_PKG_TSLIB 1
#define CONFIG_PKG_UDEV 1
#undef CONFIG_PKG_USBUTILS
#undef CONFIG_PKG_UCLINUX_CKSUM
#define CONFIG_PKG_UTIL_LINUX 1
#undef CONFIG_PKG_U_BOOT_TOOLS
#undef CONFIG_PKG_UNZIP
#undef CONFIG_PKG_VIM
#undef CONFIG_PKG_VSFTPD
#undef CONFIG_PKG_WGET
#undef CONFIG_PKG_WHICH
#define CONFIG_PKG_WIRELESS_TOOLS 1
#undef CONFIG_PKG_YAFFS_UTILS
#define CONFIG_PKG_ZLIB 1

/*
 * Target System Configuration
 */

/*
 * Options
 */
#define CONFIG_SYSCFG_HOSTNAME "homescreen"
#define CONFIG_SYSCFG_WANT_LOGIN_TTY 1
#define CONFIG_SYSCFG_LOGING_TTY "::respawn:/sbin/getty -n -l /bin/screenlogin -L ttymxc0 115200 vt100"
#define CONFIG_SYSCFG_MODLIST ""
#undef CONFIG_SYSCFG_START_DEVFSD
#define CONFIG_SYSCFG_START_NETWORK 1

/*
 * Network setup
 */

/*
 * 
 */
#define CONFIG_SYSCFG_IFACE0 1
#define CONFIG_SYSCFG_NET_INTERFACE0 "eth0"
#define CONFIG_SYSCFG_DHCPC0 1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE2

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE3

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE4
#define CONFIG_SYSCFG_DHCPC_CMD "udhcpc -b -i "
#undef CONFIG_SYSCFG_SETTIME
#define CONFIG_SYSCFG_START_SYSLOG 1
#undef CONFIG_SYSCFG_START_INETD

/*
 * Choose your Customization
 */
#undef CONFIG_CLIENT_SAGEM_PRECONFIG
#undef CONFIG_CLIENT_ORANGE_PRECONFIG
#define CONFIG_CLIENT_TELSTRA_PRECONFIG 1

/*
 * Feature Selection
 */
#define CONFIG_CONFIG_FEATURE_DLNA_PRECONFIG 1
#define CONFIG_CONFIG_FEATURE_FLASH_PRECONFIG 1

/*
 * Target Image Generation
 */

/*
 * Options
 */

/*
 * Choose your root filesystem image type
 */
#define CONFIG_DEPLOYMENT_JFFS2 1
#undef CONFIG_DEPLOYMENT_RAMDISK
#undef CONFIG_DEPLOYMENT_CRAMFS
#undef CONFIG_DEPLOYMENT_ROMFS
#undef CONFIG_DEPLOYMENT_NFS
#define CONFIG_SYSCFG_DEPLOYMENT_STYLE "JFFS2"
#undef CONFIG_SYSCFG_READONLY_FS
#define CONFIG_SYSCFG_RAM_DIRS "/tmp"
#define CONFIG_DEPLOYMENT_ROOTFS_DIR ""
#define CONFIG_DEPLOYMENT_ROOTFS_KEEPSTAGE 1
#define CONFIG_DEPLOYMENT_RM_DOCS 1
#define CONFIG_DEPLOYMENT_RM_BOOT 1
#define CONFIG_DEPLOYMENT_RM_USR_SRC 1
#define CONFIG_DEPLOYMENT_RM_USR_INCLUDE 1
#define CONFIG_DEPLOYMENT_RM_USER_DIRS "include home/sagem home/dt usr/man usr/share/info usr/share/man usr/info usr/share/locale usr/local/include usr/lib/pkgconfig usr/share/aclocal lib/pkgconfig usr/lib/glib-2.0/include usr/local/include"
#define CONFIG_DEPLOYMENT_RM_USER_FILES ""
#define CONFIG_DEPLOYMENT_RM_STATIC_LIBS 1
#define CONFIG_DEPLOYMENT_STRIP 1
#define CONFIG_DEPLOYMENT_PADDING_KB "128"
#define CONFIG_ERASE_BLOCK_SIZE "128"
#define CONFIG_CAP_UCLIBC 1
#define CONFIG_CAP_GLIBC 1
#define CONFIG_CAP_LFS_5_1 1
#define CONFIG_SYSCFG_TMPFS "tmpfs"
#define CONFIG_INITTAB_LINE "::respawn:/sbin/getty -L console 0 screen"
#define CONFIG_LTIB_RELEASE "6.2.1"
