/*
 * Automatically generated C config: don't edit
 * LTIB version: 6.2.1
 */
#define AUTOCONF_INCLUDED
#define CONFIG_CONFIG_TITLE "LTIB: Freescale IMX31 ADS reference board"
#define CONFIG_CPU "MX31"
#define CONFIG_PLATFORM_COMMENT "Freescale IMX31 ADS reference board"
#define CONFIG_VENDOR "Freescale"
#define CONFIG_PLATFORM "imx31ads"
#define CONFIG_GNUTARCH "arm"
#define CONFIG_LINTARCH "arm"
#define CONFIG_CFGHOST "arm-linux"
#define CONFIG_ENDIAN "little"

/*
 * Choose the target C library type
 */
#define CONFIG_GLIBC 1
#undef CONFIG_UCLIBC

/*
 * Choose your toolchain
 */
#define CONFIG_TOOLCHAIN1 1
#undef CONFIG_TOOLCHAIN_CUSTOM
#define CONFIG_TOOLCHAIN "tc-fsl-x86lnx-armeabi-nptl-4.1.1-6.i386.rpm"
#define CONFIG_TOOLCHAIN_PATH "/opt/freescale/usr/local/gcc-4.1.1-glibc-2.4-nptl-6/arm-none-linux-gnueabi"
#define CONFIG_TOOLCHAIN_PREFIX "arm-none-linux-gnueabi-"
#define CONFIG_TOOLCHAIN_CFLAGS "-O2 -fsigned-char -mabi=aapcs-linux -mfpu=vfp -mfloat-abi=softfp"

/*
 * Choose your Kernel
 */
#define CONFIG_KERNEL1 1
#undef CONFIG_KERNEL_DIR_BUILD
#undef CONFIG_KERNEL_NONE
#define CONFIG_PKG_KERNEL "kernel-2.6.19-mx"
#define CONFIG_PKG_KERNEL_PRECONFIG "linux-2.6.19-mx31ads.config"
#undef CONFIG_PKG_KERNEL_WANT_HEADERS
#undef CONFIG_PKG_KERNEL_WANT_CF
#undef CONFIG_PKG_KERNEL_LEAVESRC
#define CONFIG_DEPLOYMENT_ERASE_BLOCK_SIZE "128"
#define CONFIG_DISTRO "dist/lfs-5.1"

/*
 * Package selection
 */

/*
 * Package list
 */
#undef CONFIG_PKG_AUTOCONF
#undef CONFIG_PKG_AUTOMAKE
#define CONFIG_LIBC_WANTED 1
#define CONFIG_PKG_LIBC "base_libs"
#undef CONFIG_PKG_LIBC_WANT_LOCALES
#undef CONFIG_PKG_LIBC_WANT_HEADERS
#undef CONFIG_PKG_LIBC_WANT_STATIC_LIBS
#define CONFIG_PKG_ALSA_LIB 1
#define CONFIG_PKG_ALSA_UTILS 1
#define CONFIG_PKG_BASH 1
#undef CONFIG_PKG_BASH_WANT_NO_SH_SYMLINK
#undef CONFIG_PKG_BIND
#undef CONFIG_PKG_BINUTILS
#undef CONFIG_PKG_BISON
#undef CONFIG_PKG_BLUEZ_HCIDUMP
#undef CONFIG_PKG_BLUEZ_LIBS
#undef CONFIG_PKG_BLUEZ_UTILS
#undef CONFIG_PKG_BOA
#undef CONFIG_PKG_BONNIE_PLUS_PLUS
#undef CONFIG_PKG_BRIDGE_UTILS
#define CONFIG_PKG_BUSYBOX 1
#define CONFIG_PKG_BUSYBOX_PRECONFIG "busybox.config"
#undef CONFIG_PKG_BUSYBOX_WANT_CF
#undef CONFIG_PKG_BZIP2
#undef CONFIG_PKG_CAN4LINUX
#undef CONFIG_PKG_CLAMAV
#undef CONFIG_PKG_COREUTILS
#undef CONFIG_PKG_CPIO
#undef CONFIG_PKG_CRACKLIB
#undef CONFIG_PKG_CRAMFS
#undef CONFIG_PKG_DAEMONIZER
#undef CONFIG_PKG_DEVMEM2
#undef CONFIG_PKG_DHCP
#undef CONFIG_PKG_DB1
#define CONFIG_PKG_DEV 1
#undef CONFIG_PKG_DEVFSD
#undef CONFIG_PKG_DEV_NONE
#undef CONFIG_PKG_DIFFUTILS
#undef CONFIG_PKG_DIRECTFB
#undef CONFIG_PKG_DISTCC
#undef CONFIG_PKG_DOSFSTOOLS
#define CONFIG_PKG_DROPBEAR 1
#define CONFIG_PKG_DROPBEAR_WANT_URANDOM_DEV 1
#define CONFIG_PKG_DROPBEAR_WANT_NO_REV_DNS 1
#define CONFIG_PKG_DROPBEAR_WANT_NO_X11FWD 1
#undef CONFIG_PKG_DTC
#define CONFIG_PKG_E2FSPROGS 1
#undef CONFIG_PKG_ED
#undef CONFIG_PKG_ETHTOOL
#undef CONFIG_PKG_EXPAT
#undef CONFIG_PKG_FAKEROOT
#define CONFIG_PKG_FAKE_PROVIDES 1
#define CONFIG_PKG_FBSET 1
#undef CONFIG_PKG_FINDUTILS
#undef CONFIG_PKG_FLEX
#undef CONFIG_PKG_FREETYPE
#undef CONFIG_PKG_GAWK
#undef CONFIG_PKG_GCC
#define CONFIG_PKG_GDB 1
#undef CONFIG_PKG_GDB_NATIVE_WANT_ED
#define CONFIG_PKG_GDB_CROSS_WANT_ED 1
#define CONFIG_PKG_GDB_SERVER_WANT_ED 1
#undef CONFIG_PKG_GDB_M68K_BDM_WANT_ED
#undef CONFIG_PKG_GENEXT2FS
#undef CONFIG_PKG_GENROMFS
#undef CONFIG_PKG_GETTEXT
#define CONFIG_PKG_GLIB2 1
#undef CONFIG_PKG_GMP
#undef CONFIG_PKG_GREP
#undef CONFIG_PKG_GROFF
#define CONFIG_PKG_GSTREAMER_CORE 1
#define CONFIG_PKG_GST_PLUGINS_BASE 1
#define CONFIG_PKG_GST_PLUGINS_GOOD 1
#define CONFIG_PKG_GST_PLUGINS_BAD 1
#define CONFIG_PKG_GST_PLUGINS_UGLY 1
#undef CONFIG_PKG_GX200_BU_98000
#define CONFIG_PKG_HANTRO_BINARY 1
#define CONFIG_PKG_HDPARM 1
#undef CONFIG_PKG_HELLOWORLD
#undef CONFIG_PKG_HESIOD
#define CONFIG_PKG_HOTPLUG 1
#undef CONFIG_PKG_HTTPD
#undef CONFIG_PKG_I2C_TOOLS
#undef CONFIG_PKG_IPROUTE
#undef CONFIG_PKG_PIDENTD
#undef CONFIG_PKG_INETUTILS
#undef CONFIG_PKG_IPERF
#undef CONFIG_PKG_IPSEC_TOOLS
#undef CONFIG_PKG_IPSECADM
#undef CONFIG_PKG_IPTABLES
#undef CONFIG_PKG_IPUTILS
#define CONFIG_PKG_IRATTACH 1
#undef CONFIG_PKG_KBD
#define CONFIG_PKG_LESS 1
#undef CONFIG_PKG_LFS_UTILS
#undef CONFIG_PKG_LIBICONV
#define CONFIG_PKG_LIBID3TAG 1
#define CONFIG_PKG_LIBMAD 1
#define CONFIG_PKG_LIBJPEG 1
#undef CONFIG_PKG_LIBELF
#undef CONFIG_PKG_LIBPCAP
#undef CONFIG_PKG_LIBPNG
#define CONFIG_PKG_LIBOIL 1
#define CONFIG_PKG_LIBTERMCAP 1
#undef CONFIG_PKG_LIBTOOL
#define CONFIG_PKG_LIBUSB 1
#define CONFIG_PKG_LIBXML2 1
#undef CONFIG_PKG_LINUX_ATM
#undef CONFIG_PKG_LINUX_WLAN
#undef CONFIG_PKG_LKC
#undef CONFIG_PKG_LTP
#undef CONFIG_PKG_LMBENCH
#undef CONFIG_PKG_LRZSZ
#undef CONFIG_PKG_M4
#define CONFIG_PKG_MADPLAY 1
#undef CONFIG_PKG_MAKE
#undef CONFIG_PKG_MAN
#undef CONFIG_PKG_MDADM
#define CONFIG_PKG_MERGE 1
#undef CONFIG_PKG_MICROWINDOWS
#undef CONFIG_PKG_MODUTILS
#define CONFIG_PKG_MODULE_INIT_TOOLS 1
#undef CONFIG_MODUTILS_NONE
#define CONFIG_PKG_MTD_UTILS 1
#undef CONFIG_PKG_MXC_MISC
#undef CONFIG_PKG_MYSQL
#define CONFIG_PKG_NCURSES 1
#define CONFIG_PKG_NCURSES_WANT_REDUCED_SET 1
#undef CONFIG_PKG_NET_TOOLS
#undef CONFIG_PKG_NETPERF
#define CONFIG_PKG_NTPCLIENT 1
#undef CONFIG_PKG_OPENSSH
#undef CONFIG_PKG_OPENSSL
#undef CONFIG_PKG_OPENSWAN
#undef CONFIG_PKG_OPROFILE
#undef CONFIG_PKG_PATCH
#undef CONFIG_PKG_PCIUTILS
#undef CONFIG_PKG_PCMCIA_CS
#undef CONFIG_PKG_PCMCIAUTILS
#undef CONFIG_PKG_PCRE
#undef CONFIG_PKG_PERL
#undef CONFIG_PKG_PHP
#undef CONFIG_PKG_POPT
#undef CONFIG_PKG_PORTMAP
#undef CONFIG_PKG_PPP
#undef CONFIG_PKG_PROCINFO
#undef CONFIG_PKG_PROCPS
#undef CONFIG_PKG_PSMISC
#undef CONFIG_PKG_PTPD
#undef CONFIG_PKG_PYTHON
#define CONFIG_PKG_QTOPIA 1
#undef CONFIG_PKG_QTOPIA_WANT_MOUSE
#undef CONFIG_PKG_QTOPIA_WANT_CACHE_HOST_TOOLS
#undef CONFIG_PKG_RPM
#undef CONFIG_PKG_RNG_TOOLS
#undef CONFIG_PKG_RSYNC
#undef CONFIG_PKG_SAMBA
#undef CONFIG_PKG_SASH
#undef CONFIG_PKG_SCHEDUTILS
#undef CONFIG_PKG_SCREEN
#undef CONFIG_PKG_SED
#undef CONFIG_PKG_SEQ
#undef CONFIG_PKG_SETSERIAL
#define CONFIG_PKG_SKELL 1
#undef CONFIG_PKG_SKELL_WANT_TERMINFO
#define CONFIG_PKG_STRACE 1
#define CONFIG_PKG_SYSCONFIG 1
#undef CONFIG_PKG_SYSFSUTILS
#undef CONFIG_PKG_SYSKLOGD
#undef CONFIG_PKG_SYSVINIT
#undef CONFIG_PKG_TAR
#undef CONFIG_PKG_TCPDUMP
#undef CONFIG_PKG_TCP_WRAPPERS
#undef CONFIG_PKG_TEXINFO
#undef CONFIG_PKG_TIME
#define CONFIG_PKG_TIMEZONE 1
#undef CONFIG_PKG_TIMEZONE_WANT_TZCODE
#undef CONFIG_PKG_TIMEZONE_WANT_LIBTZ
#undef CONFIG_PKG_TINYLOGIN
#define CONFIG_PKG_TSLIB 1
#undef CONFIG_PKG_TVOUT_TEST_MX31
#define CONFIG_PKG_UDEV 1
#define CONFIG_PKG_USBUTILS 1
#undef CONFIG_PKG_UCLINUX_CKSUM
#undef CONFIG_PKG_UTIL_LINUX
#undef CONFIG_PKG_U_BOOT_TOOLS
#undef CONFIG_PKG_UNZIP
#undef CONFIG_PKG_VIM
#undef CONFIG_PKG_VSFTPD
#undef CONFIG_PKG_WGET
#undef CONFIG_PKG_WHICH
#define CONFIG_PKG_WIRELESS_TOOLS 1
#undef CONFIG_PKG_YAFFS_UTILS
#define CONFIG_PKG_ZLIB 1

/*
 * Target System Configuration
 */

/*
 * Options
 */
#define CONFIG_SYSCFG_HOSTNAME "freescale"
#undef CONFIG_SYSCFG_WANT_LOGIN_TTY
#define CONFIG_SYSCFG_MODLIST ""
#undef CONFIG_SYSCFG_START_DEVFSD
#define CONFIG_SYSCFG_START_NETWORK 1

/*
 * Network setup
 */

/*
 * 
 */
#define CONFIG_SYSCFG_IFACE0 1
#define CONFIG_SYSCFG_NET_INTERFACE0 "eth0"
#undef CONFIG_SYSCFG_DHCPC0
#define CONFIG_SYSCFG_IPADDR0 "172.27.161.31"
#define CONFIG_SYSCFG_NET_MASK0 "255.255.0.0"
#define CONFIG_SYSCFG_NET_BROADCAST0 "172.27.255.255"
#define CONFIG_SYSCFG_NET_GATEWAY0 "172.27.255.254"
#define CONFIG_SYSCFG_NAMESERVER0 "172.27.0.1"

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE2

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE3

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE4
#define CONFIG_SYSCFG_SETTIME 1
#define CONFIG_SYSCFG_NTP_SERVER "north-america.pool.ntp.org"
#define CONFIG_SYSCFG_START_SYSLOG 1
#define CONFIG_SYSCFG_START_INETD 1
#define CONFIG_SYSCFG_INETD_ARGS ""
#define CONFIG_SYSCFG_START_DROPBEAR_SSH 1
#define CONFIG_SYSCFG_START_QTOPIA 1

/*
 * Target Image Generation
 */

/*
 * Options
 */

/*
 * Choose your root filesystem image type
 */
#undef CONFIG_DEPLOYMENT_JFFS2
#undef CONFIG_DEPLOYMENT_RAMDISK
#undef CONFIG_DEPLOYMENT_CRAMFS
#undef CONFIG_DEPLOYMENT_ROMFS
#define CONFIG_DEPLOYMENT_NFS 1
#define CONFIG_SYSCFG_DEPLOYMENT_STYLE "NFS"
#undef CONFIG_SYSCFG_READONLY_FS
#define CONFIG_SYSCFG_RAM_DIRS ""
#define CONFIG_ERASE_BLOCK_SIZE "64"
#define CONFIG_CAP_UCLIBC 1
#define CONFIG_CAP_GLIBC 1
#define CONFIG_CAP_LFS_5_1 1
#define CONFIG_SYSCFG_TMPFS "tmpfs"
#define CONFIG_INITTAB_LINE "::respawn:/sbin/getty -L console 0 screen"
#define CONFIG_LTIB_RELEASE "6.2.1"
